alias py="python3"
alias pipf="pip freeze"
alias pipr="pip freeze > requirements.txt"
alias ponew="poetry new"
alias poin="poetry add"
alias por="poetry remove"
alias pou="poetry update"
alias porun="poetry run"
alias poinstall="poetry install"
alias poin="poetry init"
alias pol="poetry show -tlav"
alias pos="poetry shell"
alias posh="poetry search"
alias polock="poetry lock"
alias pov="poetry version"
alias poab="poetry about"

