alias ystatus="sudo systemctl status"
alias ystatusall="systemctl list-unit-files --state=enabled"
alias ylist="sudo systemctl list-unit-files"
alias ystart="sudo systemctl start"
alias ystop="sudo systemctl stop"
alias yblock="sudo systemctl mask"
alias yunblock="sudo systemctl unmask"
alias yrestart="sudo systemctl reload-or-restart"
alias yenable="sudo systemctl enable"
alias ydisable="sudo systemctl disable"

